### ISSUE TITLE
Permission denied (publickey) Issue.

### ISSUE THREAD

**Issue by Xinkle** [mingrammer/pyreportcard#6]
if server's ssh key didn't registered to github, it occur permission denied error.
because pyreport use ssh style, not https style.
```
def _make_git_protocol_url(url):
    """Make an URL with 'git@github.com' form

    Args:
        url: A repository URL

    Returns:
        Git protocol form URL
    """
    username, name = parse_url(url)
    git_protocol_url = 'git@github.com:{0}/{1}'.format(username, name)
    return git_protocol_url
```

is there specific reason to use git protocol(ssh style)?

**Comment by mingrammer** [comment]
I use the MFA to access to Github repository, So, I should use the ssh rather than https. 
But, now, this was my mistake that I did not test it on other server environments. Yes, the https can be used widely more than ssh.

So, I should set up the isolated docker environment ASAP. Or should fix the function of `_make_git_protocol_url` to use https instead of ssh. 

Do you have any ideas?

**Comment by Xinkle** [comment]
thanks to answer.
i think using https as the default option is better.
(i don't know what exactly MFA does(security factor?). but when analyzing open source(public repo), I think it's okay to use the https method.) 
but for analyzing private repository, user can select other option. (maybe user login(OAuth))

**Comment by mingrammer** [comment]
@Xinkle Yes, I'll fix them soon. Thanks for pointing out

**Comment by mingrammer** [comment]
I've resolved this issue with https://github.com/mingrammer/pyreportcard/commit/a293244875f00af427b8f63736f6cd550ddcb727. Check it plz :)

**Comment by Xinkle** [comment]
sure i'll check

**Comment by mingrammer** [comment]
Done?

**Comment by Xinkle** [comment]
@mingrammer sorry for late. i'll reply this until 10:00 pm

**Comment by Xinkle** [comment]
yes it resolved. thanks a lot
